### ISSUE TITLE
Apply git submodules

### ISSUE THREAD

**Issue by eric** [jbarnette/basis#9]
When a basis template has git submodules in it they aren't currently applied to the destination.

**Comment by jbarnette** [comment]
Agree. D'you have any thoughts on the min. git version to require? It'd be nice to use `update --init`.

**Comment by eric** [comment]
I don't have a strong opinion — I run a reasonably recent version... I would say use the goodies until people complain. There isn't a lot of problem having to turn one call into two when someone runs into problems.
